export const currentUser = {
  name: 'Alex Rivera',
  condition: 'GERD',
  streak: 4,
  initials: 'AR',
};

export const mockLogs = [
  {
    date: 'Feb 19',
    log_categories: ['food', 'symptom', 'stress', 'sleep'],
    parsed_foods: ['coffee', 'pizza'],
    parsed_symptoms: ['heartburn'],
    parsed_severity: 7,
    parsed_stress: 'high',
    parsed_sleep: 5,
    parsed_exercise: null,
    natural_summary: 'Heartburn after dinner, stressed about work deadline',
    confidence: 'high',
  },
  {
    date: 'Feb 20',
    log_categories: ['food', 'symptom', 'sleep'],
    parsed_foods: ['oatmeal', 'salad', 'chicken'],
    parsed_symptoms: [],
    parsed_severity: 3,
    parsed_stress: 'low',
    parsed_sleep: 8,
    parsed_exercise: 'light',
    natural_summary: 'Felt great today, clean eating, good sleep',
    confidence: 'high',
  },
  {
    date: 'Feb 21',
    log_categories: ['food', 'symptom', 'stress', 'sleep'],
    parsed_foods: ['coffee', 'burger', 'soda'],
    parsed_symptoms: ['heartburn', 'bloating'],
    parsed_severity: 8,
    parsed_stress: 'high',
    parsed_sleep: 5,
    parsed_exercise: null,
    natural_summary: 'Terrible reflux after lunch, high stress all day',
    confidence: 'high',
  },
  {
    date: 'Feb 22',
    log_categories: ['food', 'symptom', 'sleep', 'exercise'],
    parsed_foods: ['yogurt', 'grilled fish', 'vegetables'],
    parsed_symptoms: [],
    parsed_severity: 2,
    parsed_stress: 'low',
    parsed_sleep: 7.5,
    parsed_exercise: 'moderate',
    natural_summary: 'No issues at all, light exercise helped',
    confidence: 'high',
  },
  {
    date: 'Feb 23',
    log_categories: ['food', 'symptom', 'stress', 'sleep'],
    parsed_foods: ['coffee', 'pasta', 'wine'],
    parsed_symptoms: ['heartburn'],
    parsed_severity: 6,
    parsed_stress: 'medium',
    parsed_sleep: 6,
    parsed_exercise: null,
    natural_summary: 'Some heartburn in the evening after pasta and wine',
    confidence: 'high',
  },
  {
    date: 'Feb 24',
    log_categories: ['food', 'symptom', 'sleep'],
    parsed_foods: ['tea', 'soup', 'bread'],
    parsed_symptoms: ['bloating'],
    parsed_severity: 4,
    parsed_stress: 'low',
    parsed_sleep: 7,
    parsed_exercise: null,
    natural_summary: 'Minor bloating after lunch, otherwise okay',
    confidence: 'high',
  },
  {
    date: 'Feb 25',
    log_categories: ['food', 'symptom', 'stress', 'sleep'],
    parsed_foods: ['coffee', 'spicy food', 'beer'],
    parsed_symptoms: ['heartburn', 'chest pain'],
    parsed_severity: 8,
    parsed_stress: 'high',
    parsed_sleep: 4,
    parsed_exercise: null,
    natural_summary: "Awful night, couldn't sleep from the burning sensation",
    confidence: 'high',
  },
  {
    date: 'Feb 26',
    log_categories: ['food', 'symptom', 'sleep', 'exercise'],
    parsed_foods: ['herbal tea', 'rice', 'steamed vegetables'],
    parsed_symptoms: [],
    parsed_severity: 3,
    parsed_stress: 'low',
    parsed_sleep: 8,
    parsed_exercise: 'light',
    natural_summary: 'Reset day, clean eating, feeling much better',
    confidence: 'high',
  },
  {
    date: 'Feb 27',
    log_categories: ['food', 'symptom', 'stress', 'sleep'],
    parsed_foods: ['coffee', 'sandwich', 'chips'],
    parsed_symptoms: ['heartburn'],
    parsed_severity: 5,
    parsed_stress: 'medium',
    parsed_sleep: 6.5,
    parsed_exercise: null,
    natural_summary: 'Midday discomfort, medium stress from meetings',
    confidence: 'high',
  },
  {
    date: 'Feb 28',
    log_categories: ['food', 'symptom', 'sleep', 'exercise'],
    parsed_foods: ['oatmeal', 'banana', 'water'],
    parsed_symptoms: [],
    parsed_severity: 2,
    parsed_stress: 'low',
    parsed_sleep: 8,
    parsed_exercise: 'moderate',
    natural_summary: 'Good day overall, best diet choices this week',
    confidence: 'high',
  },
  {
    date: 'Mar 1',
    log_categories: ['food', 'symptom', 'stress', 'sleep'],
    parsed_foods: ['coffee', 'pizza', 'soda'],
    parsed_symptoms: ['heartburn', 'bloating'],
    parsed_severity: 7,
    parsed_stress: 'high',
    parsed_sleep: 5,
    parsed_exercise: null,
    natural_summary: 'Work deadline stress combined with bad food choices',
    confidence: 'high',
  },
  {
    date: 'Mar 2',
    log_categories: ['food', 'symptom', 'sleep', 'exercise'],
    parsed_foods: ['herbal tea', 'salad', 'chicken'],
    parsed_symptoms: [],
    parsed_severity: 1,
    parsed_stress: 'low',
    parsed_sleep: 8,
    parsed_exercise: 'moderate',
    natural_summary: 'Best day in weeks, everything dialed in',
    confidence: 'high',
  },
  {
    date: 'Mar 3',
    log_categories: ['food', 'symptom', 'sleep'],
    parsed_foods: ['coffee', 'toast', 'soup'],
    parsed_symptoms: ['heartburn'],
    parsed_severity: 4,
    parsed_stress: 'low',
    parsed_sleep: 7,
    parsed_exercise: null,
    natural_summary: 'Slight discomfort after morning coffee',
    confidence: 'high',
  },
  {
    date: 'Mar 4',
    log_categories: ['food', 'symptom', 'stress', 'sleep'],
    parsed_foods: ['coffee', 'takeout', 'dessert'],
    parsed_symptoms: ['heartburn', 'bloating'],
    parsed_severity: 6,
    parsed_stress: 'medium',
    parsed_sleep: 6,
    parsed_exercise: null,
    natural_summary: 'Reflux mid-evening after takeout and dessert',
    confidence: 'high',
  },
];

export const mockInsights = [
  {
    id: 1,
    icon: '⚡',
    title: 'Stress amplifies your symptoms 2×',
    body: 'Your average pain level on high-stress days is 7.2 vs 2.8 on low-stress days. The difference is consistent across your 14 logs — stress is your strongest predictor.',
    clinicalContext: 'Psychological stress activates the gut-brain axis, increasing visceral hypersensitivity and esophageal acid exposure in GERD patients. (PMC10635461)',
    confidence: 87,
    tag: 'Strong signal',
    tagColor: 'accent',
  },
  {
    id: 2,
    icon: '☕',
    title: 'Coffee on 10 of your 14 days',
    body: 'Coffee appears on every high pain day (≥6). On the 4 days without coffee, average pain level was 2.1. Your clearest days all had herbal tea instead.',
    clinicalContext: 'Caffeine relaxes the lower esophageal sphincter (LES), reducing its barrier function against gastric acid reflux. (PMID: 32744297)',
    confidence: 74,
    tag: 'High confidence',
    tagColor: 'danger',
  },
  {
    id: 3,
    icon: '😴',
    title: 'Under 6h sleep → next-day flare',
    body: 'Your 5 worst symptom days followed nights with ≤5 hours of sleep. Nights with 7+ hours preceded days averaging a pain level of 2.8.',
    clinicalContext: 'Sleep deprivation increases esophageal acid exposure time and reduces mucosal recovery in GERD patients. (PMC8521548)',
    confidence: 61,
    tag: 'Combined trigger',
    tagColor: 'amber',
  },
];

export const mockConversationHistory = [
  {
    id: 1,
    question: "Why was last week so bad?",
    answer: "Your three worst days last week all had coffee in the morning and under 5 hours sleep the night before. On your two good days, you had neither. Coffee alone raises your average pain level from 2.1 to 5.8, but combined with poor sleep it jumps to 7.2.",
    timestamp: "Mar 4, 8:32pm",
    tools_used: ["query_logs", "correlate", "fetch_research"],
  },
  {
    id: 2,
    question: "Is stress making things worse?",
    answer: "Yes, significantly. On high-stress days your average pain level is 7.2 versus 2.8 on low-stress days. That is your strongest single predictor, even stronger than coffee. The gut-brain axis research backs this up directly.",
    timestamp: "Mar 3, 9:14pm",
    tools_used: ["correlate", "fetch_research"],
  },
];

// Mock API response shape for POST /logs/preview
export const mockPreviewResponse = {
  log_categories: ['food', 'symptom', 'stress', 'sleep'],
  parsed_foods: ['coffee', 'takeout', 'dessert'],
  parsed_symptoms: ['heartburn', 'bloating'],
  parsed_severity: 6,
  parsed_stress: 'medium',
  parsed_sleep: 6,
  parsed_exercise: null,
  confidence: 'medium',
  natural_summary: 'Coffee and takeout, reflux mid-evening, moderate stress',
  missing_critical_field: null,
};
